en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: |
    <div>
    Copyright &copy; 2021-{{< current_year >}} Gramine contributors.

    Legal disclaimers, required by our sponsors:<br>
    Any opinions, findings, and conclusions or recommendations expressed in
    this material are ours alone, and do not necessarily reflect the views of
    our sponsors. All product names, logos, and brands are property of their
    respective owners. All company, product and service names used in this
    website are for identification purposes only. Use of these names, logos,
    and brands does not imply endorsement.
    </div>

  title: "Gramine"
  params:
    description: "Site Description"
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 1
    - identifier: "maintainers"
      name: "Maintainers"
      url: "/maintainers/"
      weight: 2
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 3
    - identifier: "docs"
      name: "Docs"
      url: "https://gramine.readthedocs.io/en/latest/"
      weight: 4
    - identifier: "github"
      name: "GitHub"
      url: "https://github.com/gramineproject"
      weight: 5
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 6
