######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/gramine-logo.svg"
logo_on_black: "/img/gramine-logo.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/gramine-social.jpg"]

github:
  repo_url: "https://github.com/gramineproject/gramineproject.io/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/gramineproject/gramine"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
