# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/configure-pages@v4
      - run: |
          sudo apt-get -y satisfy '
            hugo,
            npm,
          '
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: public/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
